version: '3.4'

networks:
  shared-network:
    name: shared-network
    driver: bridge

volumes:
  postgres-data:

services:
  storiescollection:
    image: ${DOCKER_REGISTRY-}storiescollection
    build:
      context: .
      dockerfile: StoriesCollection/Dockerfile
    ports:
      - "8443:80"
    networks: 
      - shared-network
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=stories;user id=admin;Password=password
    depends_on:
      - "postgres"

  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432"
    restart: always
    networks: 
      - shared-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stories
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./StoriesCollection/Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    networks: 
      - shared-network
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped